#Nome microserviço GATEWAY
spring:
  application:
    name: mscloudgateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

#Porta server GATEWAY
server:
  port: 8080

#Localização do Discovery EUREKA
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
